# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8fece797237186e6479f3d0ab407a32510777faf80cbfbb2776153907e0c854d830c32a1e6106b216bfdc47128f44d32b1086306d13ebae7c0be6ae74ad1d7a

test:
  secret_key_base: 558853a5b2f99eff8dbe6c01c276aa007592103e54c6e0c2a1a37c4c4cff0d26eb701605d0ccca858ad85b09556fba9af219fc13c754e1b74a00e5deca846219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
